FROM node:argon
MAINTAINER Shun Takahashi <@shuntksh>

RUN npm install -g yarn forever

RUN groupadd -r app && useradd -r -g app app 

COPY . /opt/binaryscanr
WORKDIR /opt/binaryscanr

RUN yarn
RUN npm run build

EXPOSE 3000/tcp
ENTRYPOINT exec forever dist/binaryscanr.js
